# Netlify configuration for Stripe Dashboard UXR Prototype

[build]
  # No build process needed for static prototype
  command = "echo 'No build required'"
  publish = "."

[functions]
  # Directory for serverless functions
  directory = "api"

[[redirects]]
  # SPA routing - handle direct navigation to prototype pages
  from = "/prototypes/*"
  to = "/prototypes/:splat"
  status = 200

# Headers for CORS and caching
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=3600"